name: Generate Snake

# Controls when the action will run.
on:
  # Schedule runs every 6 hours.
  schedule:
    - cron: "0 */6 * * *" 
  # Allows you to manually trigger the workflow.
  workflow_dispatch:

# Define the jobs in this workflow.
jobs:
  build:
    # The type of machine the workflow will run on.
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository.
      - uses: actions/checkout@v2

      # Generates the snake contribution SVG using the Platane/snk GitHub Action.
      - uses: Platane/snk@v2
        with:
          github_user_name: Vanohra # Your GitHub username
          outputs: dist/snake.svg

      # Push the generated snake SVG to the output branch of your repository.
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # This is the branch that will store the SVG.
          build_dir: dist        # The directory where the snake SVG is saved.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
